Update index.html
Added package name parameter to `cabal init` since it'll fail without it (Cabal 3.2.0)

```
PS D:\User\Documents\Programming\Haskell\MiscTests\cabal> cabal init

Guessing dependencies...

Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating Setup.hs...
Generating CHANGELOG.md...
Generating Main.hs...
Error: no package name provided.
```